DROP TABLE PERSON
DROP SEQUENCE ID

DROP SEQUENCE Bairros
drop index BAIRROS_PK;
drop table Bairros;

DROP SEQUENCE CIDADES;
drop index CIDADES_PK;
drop table Cidades;

DROP SEQUENCE CEPS;
drop index ASSOCCEPSCID_FK;
drop index ASSOCCEPBAI_FK;
drop index CEPS_PK;
drop table Ceps;

DROP SEQUENCE AUDITORES;
drop index AUDITORES_PK;
drop table Auditores;

DROP SEQUENCE CLIENTES;
drop index CLIENTES_PK;
drop table Clientes;

DROP SEQUENCE COLABORADORES;
drop index COLABORADORES_PK;
drop table Colaboradores;

DROP SEQUENCE CERTIFICADORAS;
drop index ASSOCIATION_3_FK;
drop index CERTIFICADORAS_PK;
drop table Certificadoras;


DROP SEQUENCE AUDITORIAS;
drop index ASSOCIATION_8_FK;
drop index ASSOCCERTAUDITORIA_FK;
drop index AUDITORIAS_PK;
drop table Auditorias;

DROP SEQUENCE EQUIPEAUDITORES;
drop index ASSOCAUDITEQUIPE_FK;
drop index ASSOCAUDITORIAEQUIPE_FK;
drop index EQUIPEAUDITORES_PK;
drop table EQUIPEAUDITORES;

DROP SEQUENCE CHECKLIST;
drop index ASSOCCOLACHKLST_FK;
drop index ASSOCEQUICHKLIST_FK;
drop index ASSOCAUDITORIACHKLIST_FK;
drop index CHECKLIST_PK;
drop table CheckList;

DROP SEQUENCE NAOCONFORMIDADES;
drop index ASSOCCOLANC_FK;
drop index ASSOCCHKNC_FK;
drop index NAOCONFORMIDADEDS_PK;
drop table NaoConformidades;

DROP SEQUENCE OCORRENCIAS;
drop index ASSOCCOLAOCO_FK;
drop index ASSOCCHKOCO_FK;
drop index OCORRENCIAS_PK;
drop table Ocorrencias;

CREATE SEQUENCE UF;
drop domain UF;
